// Alerts
export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

// Register and Login User
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const GET_PROFILE = 'GET_PROFILE';
export const GET_PROFILES = 'GET_PROFILES';
export const GET_ONE_USER_PROFILE = 'GET_ONE_USER_PROFILE';
export const PROFILE_ERROR = 'PROFILE_ERROR';
export const CLEAR_PROFILE = 'CLEAR_PROFILE';
export const EDIT_USER_AVATAR = "EDIT_USER_AVATAR";

// Genre
export const GET_GENRES = 'GET_GENRES';
export const GET_OTHER_USER_GENRE = 'GET_OTHER_USER_GENRE';
export const ADD_GENRE = 'ADD_GENRE';
export const DELETE_GENRE_AND_GET_GENRES = 'DELETE_GENRE_AND_GET_GENRES';

// Artist
export const CLEAR_VINYL_COLLECTION = 'CLEAR_VINYL_COLLECTION';
export const GET_ARTISTS = 'GET_ARTISTS';
export const GET_ARTISTS_WITH_NO_ALBUMS = 'GET_ARTISTS_WITH_NO_ALBUMS';
export const GET_ARTISTS_WITH_ALBUMS = 'GET_ARTISTS_WITH_ALBUMS';
export const GET_OTHER_USER_ARTIST_WITH_ALBUMS = 'GET_OTHER_USER_ARTIST_WITH_ALBUMS';
export const GET_ONE_ARTIST = 'GET_ONE_ARTIST';
export const GET_ONE_ARTIST_FOR_SONGS = 'GET_ONE_ARTIST_FOR_SONGS';
export const CLEAR_ONE_ARTIST = 'CLEAR_ONE_ARTIST';
export const GET_OTHER_USER_ONE_ARTIST = 'GET_OTHER_USER_ONE_ARTIST';
export const CLEAR_OTHER_USER_ONE_ARTIST = 'CLEAR_OTHER_USER_ONE_ARTIST';
export const DELETE_ARTIST_AND_GET_ARTISTS = 'DELETE_ARTISTS_AND_GET_ARTISTS';
export const DELETE_ALBUM_AND_GET_ARTISTS = 'DELETE_ALBUM_AND_GET_ARTISTS';
export const DELETE_SONG_AND_GET_ARTISTS = 'DELETE_SONG_AND_GET_ARTISTS';

// Pagination
export const UPDATE_ARTIST_CURRENT_PAGE = 'UPDATE_ARTIST_CURRENT_PAGE';
export const UPDATE_ARTIST_PER_PAGE = 'UPDATE_ARTIST_PER_PAGE';
export const RESET_CURRENT_PAGE = 'RESET_CURRENT_PAGE';

// Artist Query
export const CHANGE_GENRE = 'CHANGE_GENRE';
export const CLEAR_GENRE = 'CLEAR_GENRE';
export const SORT_ARTIST = 'SORT_ARTIST';
export const BEGINS_WITH = 'BEGINS_WITH';
export const CLEAR_BEGINS_WITH = 'CLEAR_BEGINS_WITH';
export const SEARCH_ARTIST = 'SEARCH_ARTIST';
export const CLEAR_SEARCH_ARTIST = 'CLEAR_SEARCH_ARTIST';